# Generated by Django 2.2.4 on 2021-05-25 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0003_auto_20210525_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='released_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
