# Generated by Django 2.2.4 on 2021-05-25 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0004_auto_20210526_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='released_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
