# Generated by Django 2.2.4 on 2021-05-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_show_app', '0005_auto_20210526_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='released_date',
            field=models.DateField(),
        ),
    ]
