# Generated by Django 2.2.4 on 2021-05-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='name',
            new_name='last_name',
        ),
        migrations.AddField(
            model_name='users',
            name='email',
            field=models.CharField(default='email', max_length=255),
        ),
        migrations.AddField(
            model_name='users',
            name='first_name',
            field=models.CharField(default='name', max_length=255),
        ),
    ]
